name: "action-maven-publish"
author: "Jesper Skov (jskov@mada.dk)"
description: "Publish maven artifacts to Nexus"

inputs:
  log_level:
    description: 'Log level (for JUL framework)'
    required: false
    default: 'info'
    type: choice
    options:
      - info
      - finest

  search_directory:
    required: true
    description: "FIXME search dir"

  companion_suffixes:
    required: false
    description: "FIXME companion suffixes"
    default: ".jar, .module, -javadoc.jar, -sources.jar"

  signing_key:
    required: true
    description: "FIXME signing key"

  signing_key_secret:
    required: true
    description: "FIXME secret"

  ossrh_username:
    required: true
    description: "FIXME OSSRH_USERNAME"

  ossrh_token:
    required: true
    description: "FIXME OSSRH_TOKEN"

  target_action:
    description: "The action to take for bundles after upload"
    required: false
    default: 'keep'
    type: choice
    options:
      - drop
      - keep
      - promote_or_keep

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
          java-version: '21'
          distribution: 'temurin'

    - name: run publisher
      shell: bash
      run: |-
        classes_dir=$(mktemp -d)
        (cd ${{ github.action_path }}/src/main/java ; javac -d $classes_dir $(find . -name \*.java))
        cp ${{ github.action_path }}/src/main/resources/logging.properties $classes_dir
        java -cp $classes_dir dk.mada.action.ActionNexusPublisher
        rm -rf $classes_dir
      env:
        SEARCH_DIR: ${{ inputs.search_directory }}
        COMPANION_SUFFIXES: ${{ inputs.companion_suffixes }}
        SIGNING_KEY: ${{ inputs.signing_key }}
        SIGNING_KEY_SECRET: ${{ inputs.signing_key_secret }}
        LOG_LEVEL: ${{ inputs.log_level }}
        OSSRH_USERNAME: ${{ inputs.ossrh_username }}
        OSSRH_TOKEN: ${{ inputs.ossrh_token }}
        TARGET_ACTION: ${{ inputs.target_action }}
        