name: "action-maven-publish"
author: "Jesper Skov (jskov@mada.dk)"
description: "Publish maven artifacts to Maven Central via Portal Publisher API"

inputs:
  search_directory:
    required: true
    description: "The directory to search for POM files"

  companion_suffixes:
    required: false
    description: "The companion files to include with found POM files, comma-separated"
    default: ".jar, .module, -javadoc.jar, -sources.jar"

  signing_key:
    required: true
    description: "The private GPG signing key"

  signing_key_secret:
    required: true
    description: "The secret for the GPG signing key"

  portal_username:
    required: true
    description: "The Portal login name"

  portal_token:
    required: true
    description: "The Portal token"

  target_action:
    description: "The action to take for bundles after upload"
    required: false
    default: 'keep'
    type: choice
    options:
      - drop
      - keep
      - promote_or_keep

  log_level:
    description: 'Log level (for JUL framework)'
    required: false
    default: 'info'
    type: choice
    options:
      - info
      - fine
      - finest

  initial_pause:
    required: false
    description: "The per-bundle initial pause (in seconds) before polling for completion state changes."
    default: 45

  loop_pause:
    required: false
    description: "The per-bundle loop pause (in seconds) between polling for completion state changes."
    default: 15

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5
      with:
          java-version: '21'
          distribution: 'temurin'

    - name: run publisher
      shell: bash
      run: |-
        classes_dir=$(mktemp -d)
        (cd ${{ github.action_path }}/src/main/java ; javac -d $classes_dir $(find . -name \*.java))
        cp ${{ github.action_path }}/src/main/resources/logging.properties $classes_dir
        java -cp $classes_dir dk.mada.action.ActionNexusPublisher
        rm -rf $classes_dir
      env:
        SEARCH_DIR: ${{ inputs.search_directory }}
        COMPANION_SUFFIXES: ${{ inputs.companion_suffixes }}
        SIGNING_KEY: ${{ inputs.signing_key }}
        SIGNING_KEY_SECRET: ${{ inputs.signing_key_secret }}
        LOG_LEVEL: ${{ inputs.log_level }}
        PORTAL_USERNAME: ${{ inputs.portal_username }}
        PORTAL_TOKEN: ${{ inputs.portal_token }}
        TARGET_ACTION: ${{ inputs.target_action }}
        INITIAL_PAUSE: ${{ inputs.initial_pause }}
        LOOP_PAUSE: ${{ inputs.loop_pause }}
