name: "nexus-publish"
author: "Jesper Skov (jskov@mada.dk)"
description: "Publish artifacts to Nexus"

inputs:
  signing_key:
    required: true
    description: "FIXME signing key"

  signing_key_secret:
    required: true
    description: "FIXME secret"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
          java-version: '21'
          distribution: 'temurin'

    - name: run publisher
      shell: bash
      run: |-
        classes_dir=$(mktemp -d)
        (cd ${{ github.action_path }}/src/main/java ; javac -d $classes_dir $(find . -name \*.java))
        java -cp $classes_dir dk.mada.action.NexusPublisher arg1 arg2 argN
        rm -rf $classes_dir
      env:
        SIGNING_KEY: ${{ inputs.signing_key }}
        SIGNING_KEY_SECRET: ${{ inputs.signing_key_secret }}
